name: Test

on:
  push:
    branches: ['main']
  pull_request:
    branches: ['main']

jobs:
  unit-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 23
      - name: Install dependencies
        run: npm ci
      - name: Build the code
        run: npm run build
      - name: Run unit tests
        run: npm run test:unit

  integration-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 23
      - name: Install dependencies
        run: npm ci
      - name: Build the code
        run: npm run build
      - name: Install Playwright Browsers
        run: npx playwright install --with-deps
      - name: Run integration tests
        run: npm run test:integration
